print("---PAINEL DE ATENDIMENTO---")
fila_espera = ("senha 01", "senha 02", "senha 03", "senha 04")
total = len(fila_espera)
print(f"O próximo paciente a ser atendido é: {fila_espera[0]}")
print(f"O segundo paciente  da fila é:{fila_espera[1]}")
print(f"Total aguardando: {total}")
